# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: 면접 질문 리스트
email: ddakshe@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  면접 질문 리스트 입니다.
  가장 답변하기 어려운 질문은 무엇일까요? 바로 "너테출??"
baseurl: "/blog-interview" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site
twitter_username: ddakshe
github_username:  ddakshe

# Build settings
markdown: kramdown
